### ISSUE TITLE
When zooming the timeline, videos loose their position on the timeline

### ISSUE THREAD

**Issue by currentsound** [Pablituuu/react-video-editor#3]
Steps to re-create bug:

1. Add two or more videos
2. Move one of them to any position on the timeline
3. Press zoom + or minus button to zoom on the timeline

Result: All videos snap to the start of the timeline and loose their previous position.

**Comment by lh-sn** [comment]
@currentsound thanks for reporting it, it should get fixed in the next release.

**Comment by Pablituuu** [comment]
Fixed in designcombo version 0.5.0
